name: tempo_fy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  just_audio: ^0.9.37
  rxdart: ^0.27.7
  youtube_player_flutter: ^9.0.0
  dio: ^5.4.2+1
  miniplayer: ^1.0.1
  flutter_riverpod: ^0.13.1+1
  http: ^1.2.1
  timeago: ^3.0.2
  pip_view: ^0.9.7
  google_sign_in: ^6.2.1
  googleapis: ^13.0.0
  intl: ^0.19.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  marquee: ^2.2.3
  # firebase_auth: ^5.1.0
  # firebase_core: ^3.1.0
  provider: ^6.1.2
  audio_service: ^0.18.14
  audio_session: ^0.1.20
  palette_generator: ^0.3.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    # - assets/yt_logo_dark.png
